#include <stdlib.h>
#include <stdio.h>
int main(){
    // int scecretNumber = rand();    // Generate a random number between 0 and RAND_MAX=2147483647

    /*time(NULL) returns the current calendar time as a time_t object.
    srand seeds the random number generator with the current time. 
    This ensures that the sequence of random numbers generated by 
    rand will be different each time the program is run.*/
    srand(time(NULL));

     // Generate a random number in a specific range, e.g., 1 to 100

    int lower = 1;
    int upper = 100;
    int randomInRange = (rand() % (upper - lower + 1)) + lower;

    int guess = NULL;
    int guessCount = 0;

   
    while (guess != randomInRange){
        puts("Guess the secret number: ");
        scanf("%d", &guess);
        guessCount++;
        if(guess > randomInRange)
        {
            puts("Too high!\n");
        }
        else if (guess < randomInRange)
        {
            puts("Too low!\n");
        }else{
            printf("Correct! The secret number was %d\n You guessed %d times", randomInRange, guessCount);
            break;
        }
        
        
        
    }
    



    return 0;
}